# Generated by Django 5.0 on 2024-12-16 19:29

from django.db import migrations


class Migration(migrations.Migration):
    SQL = """
        INSERT INTO orders_status(created_at, updated_at, active, name, description) VALUES
            (now(), now(), True, 'Pending', 'Order is pending'),
            (now(), now(), True, 'Processing', 'Order is processing'),
            (now(), now(), True, 'Completed', 'Order is completed'),
            (now(), now(), True, 'Cancelled', 'Order is cancelled')
        ON CONFLICT DO NOTHING;
    """

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(SQL, reverse_sql=migrations.RunSQL.noop)
    ]
