# Generated by Django 5.0 on 2024-12-15 04:51

from django.db import migrations


class Migration(migrations.Migration):
    SQL = """
        INSERT INTO menus_categories(created_at, updated_at, active, name, description) VALUES
            (now(), now(), True, 'Desayunos', 'Desayunos'),
            (now(), now(), True, 'Almuerzos', 'Almuerzos'),
            (now(), now(), True, 'Cenas', 'Cenas'),
            (now(), now(), True, 'Postres', 'Postres'),
            (now(), now(), True, 'Bebidas', 'Bebidas'),
            (now(), now(), True, 'Snacks', 'Snacks'),
            (now(), now(), True, 'Comidas rapidas', 'Comidas rapidas'),
            (now(), now(), True, 'Comidas tipicas', 'Comidas tipicas'),
            (now(), now(), True, 'Comidas gourmet', 'Comidas gourmet'),
            (now(), now(), True, 'Comidas saludables', 'Comidas saludables'),
            (now(), now(), True, 'Comidas vegetarianas', 'Comidas vegetarianas'),
            (now(), now(), True, 'Comidas veganas', 'Comidas veganas'),
            (now(), now(), True, 'Comidas para diabeticos', 'Comidas para diabeticos'),
            (now(), now(), True, 'Comidas para celiacos', 'Comidas para celiacos'),
            (now(), now(), True, 'Comidas para hipertensos', 'Comidas para hipertensos'),
            (now(), now(), True, 'Comidas para deportistas', 'Comidas para deportistas'),
            (now(), now(), True, 'Comidas para embarazadas', 'Comidas para embarazadas'),
            (now(), now(), True, 'Comidas para niños', 'Comidas para niños'),
            (now(), now(), True, 'Comidas para adultos mayores', 'Comidas para adultos mayores'),
            (now(), now(), True, 'Comidas para mascotas', 'Comidas para mascotas')
        ON CONFLICT DO NOTHING;

        INSERT INTO menus(created_at, updated_at, active, name, description, price, preparation_time, available, image_url, restaurants_id) VALUES
            (now(), now(), True, 'Huevos con tocino', 'Huevos con tocino', 100.0, 10, true, 'https://www.example.com/huevos_con_tocino.jpg', 1),
            (now(), now(), True, 'Pancakes', 'Pancakes', 200.0, 15, true, 'https://www.example.com/pancakes.jpg', 2),
            (now(), now(), True, 'Waffles', 'Waffles', 300.0, 20, true, 'https://www.example.com/waffles.jpg', 3),
            (now(), now(), True, 'Hot cakes', 'Hot cakes', 400.0, 25, true, 'https://www.example.com/hot_cakes.jpg', 4),
            (now(), now(), True, 'Tostadas francesas', 'Tostadas francesas', 500.0, 30, true, 'https://www.example.com/tostadas_francesas.jpg', 5),
            (now(), now(), True, 'Ensalada César', 'Ensalada con pollo y aderezo César', 150.0, 12, true, 'https://www.example.com/ensalada_cesar.jpg', 6),
            (now(), now(), True, 'Sopa de pollo', 'Sopa de pollo con vegetales', 120.0, 18, true, 'https://www.example.com/sopa_de_pollo.jpg', 7),
            (now(), now(), True, 'Pizza Margarita', 'Pizza con tomate, albahaca y queso mozzarella', 350.0, 22, true, 'https://www.example.com/pizza_margarita.jpg', 8),
            (now(), now(), True, 'Burritos', 'Burritos rellenos de carne, arroz y frijoles', 250.0, 20, true, 'https://www.example.com/burritos.jpg', 9),
            (now(), now(), True, 'Hamburguesa con papas', 'Hamburguesa con carne, lechuga, tomate y papas fritas', 450.0, 18, true, 'https://www.example.com/hamburguesa_con_papas.jpg', 10),
            (now(), now(), True, 'Tacos al pastor', 'Tacos con carne al pastor y piña', 180.0, 10, true, 'https://www.example.com/tacos_al_pastor.jpg', 11),
            (now(), now(), True, 'Spaghetti Bolognesa', 'Spaghetti con salsa Bolognesa y carne', 300.0, 20, true, 'https://www.example.com/spaghetti_bolognesa.jpg', 12),
            (now(), now(), True, 'Sushi', 'Rollos de sushi con pescado fresco', 600.0, 30, true, 'https://www.example.com/sushi.jpg', 13),
            (now(), now(), True, 'Paella', 'Paella con mariscos y arroz', 700.0, 35, true, 'https://www.example.com/paella.jpg', 14),
            (now(), now(), True, 'Churros', 'Churros con azúcar y canela', 150.0, 15, true, 'https://www.example.com/churros.jpg', 15),
            (now(), now(), True, 'Ceviche', 'Ceviche con pescado fresco y limón', 200.0, 20, true, 'https://www.example.com/ceviche.jpg', 16),
            (now(), now(), True, 'Ramen', 'Ramen con cerdo y huevo', 550.0, 28, true, 'https://www.example.com/ramen.jpg', 17),
            (now(), now(), True, 'Sopa miso', 'Sopa miso con tofu y algas', 120.0, 10, true, 'https://www.example.com/sopa_miso.jpg', 1),
            (now(), now(), True, 'Tartar de atún', 'Tartar de atún fresco con aguacate', 450.0, 15, true, 'https://www.example.com/tartar_atun.jpg', 2),
            (now(), now(), True, 'Curry japonés', 'Arroz con curry y pollo', 500.0, 30, true, 'https://www.example.com/curry_japones.jpg', 3),
            (now(), now(), True, 'Pato a la naranja', 'Pato con salsa de naranja y arroz', 800.0, 40, true, 'https://www.example.com/pato_naranja.jpg', 4),
            (now(), now(), True, 'Bifes de chorizo', 'Bifes de chorizo a la parrilla', 650.0, 25, true, 'https://www.example.com/bifes_chorizo.jpg', 5),
            (now(), now(), True, 'Lasagna', 'Lasagna con carne, queso y salsa de tomate', 350.0, 20, true, 'https://www.example.com/lasagna.jpg', 6),
            (now(), now(), True, 'Fish and chips', 'Pescado frito con papas', 300.0, 15, true, 'https://www.example.com/fish_and_chips.jpg', 7),
            (now(), now(), True, 'Tarta de manzana', 'Tarta de manzana con crema pastelera', 180.0, 10, true, 'https://www.example.com/tarta_manzana.jpg', 8),
            (now(), now(), True, 'Lasaña vegetariana', 'Lasaña con verduras y queso', 400.0, 25, true, 'https://www.example.com/lasana_vegetariana.jpg', 9),
            (now(), now(), True, 'Croquetas de jamón', 'Croquetas de jamón y queso', 150.0, 12, true, 'https://www.example.com/croquetas_jamon.jpg', 10),
            (now(), now(), True, 'Panna cotta', 'Panna cotta con salsa de frutos rojos', 200.0, 15, true, 'https://www.example.com/panna_cotta.jpg', 11),
            (now(), now(), True, 'Goulash', 'Goulash húngaro con carne de res', 550.0, 35, true, 'https://www.example.com/goulash.jpg', 12),
            (now(), now(), True, 'Sopa de mariscos', 'Sopa con mariscos frescos', 450.0, 30, true, 'https://www.example.com/sopa_mariscos.jpg', 13)
        ON CONFLICT DO NOTHING;
    """


    dependencies = [
        ('menus', '0001_initial'),
        ('restaurants', '0002_auto_20241215_0411'),
    ]

    operations = [
        migrations.RunSQL(SQL, reverse_sql=migrations.RunSQL.noop),
    ]
