# Generated by Django 5.0 on 2024-12-15 03:56

from django.db import migrations
    
class Migration(migrations.Migration):
    SQL = """
        INSERT INTO users_typology_types(created_at, updated_at, active, name, descripcion) VALUES
            (now(), now(), True, 'Admin', 'Administrador del sistema'),
            (now(), now(), True, 'Trabajador', 'Trabajador del sistema'),
            (now(), now(), True, 'Cliente', 'Cliente del sistema')
        ON CONFLICT DO NOTHING;

        INSERT INTO users(created_at, updated_at, active, first_name, last_name, email, phone, default_adress, restaurants_id, typology_id) VALUES
            (now(), now(), True, 'Juan', 'Perez', 'juanperez@example.com', '12345678', 'Calle 1', 1, 1),
            (now(), now(), True, 'Maria', 'Gonzalez', 'mariagonzalez@example.com', '87654321', 'Calle 2', 2, 2),
            (now(), now(), True, 'Pedro', 'Rodriguez', 'pedrorodriguez@example.com', '87654321', 'Calle 3', 3, 2),
            (now(), now(), True, 'Jose', 'Martinez', 'josemartinez@example.com', '87654321', 'Calle 4', 4, 2),
            (now(), now(), True, 'Ana', 'Hernandez', 'anahernandez@example.com', '87654321', 'Calle 5', 5, 2),
            (now(), now(), True, 'Luis', 'Lopez', 'luislopez@example.com', '87654321', 'Calle 6', 6, 3),
            (now(), now(), True, 'Carlos', 'Torres', 'carlostorres@example.com', '87654321', 'Calle 7', 7, 3),
            (now(), now(), True, 'Sofia', 'Diaz', 'sofiadiaz@example.com', '87654321', 'Calle 8', 8, 3),
            (now(), now(), True, 'Fernando', 'Gomez', 'fernandogomez@example.com', '87654321', 'Calle 9', 9, 3),
            (now(), now(), True, 'Laura', 'Vargas', 'lauravargas@example.com', '87654321', 'Calle 10', 10, 3),
            (now(), now(), True, 'Diana', 'Jimenez', 'dianajimenez@example.com', '87654321', 'Calle 11', 11, 3),
            (now(), now(), True, 'Jorge', 'Moreno', 'jorgemoreno@example.com', '87654321', 'Calle 12', 12, 3),
            (now(), now(), True, 'Gabriela', 'Perez', 'gabrielaperez@example.com', '87654321', 'Calle 13', 13, 3),
            (now(), now(), True, 'Ricardo', 'Gonzalez', 'ricardogonzalez@example.com', '87654321', 'Calle 14', 14, 3),
            (now(), now(), True, 'Mariana', 'Rodriguez', 'marianarodriguez@example.com', '87654321', 'Calle 15', 1, 3),
            (now(), now(), True, 'Alejandro', 'Martinez', 'alejandromartinez@example.com', '87654321', 'Calle 16', 2, 3),
            (now(), now(), True, 'Carmen', 'Hernandez', 'carmenhernandez@example.com', '87654321', 'Calle 17', 3, 3)
        ON CONFLICT DO NOTHING;

        INSERT INTO users_additional_data(created_at, updated_at, active, password, user_id) VALUES
            (now(), now(), True, 'asd123', 1),
            (now(), now(), True, 'asd123', 2),
            (now(), now(), True, 'asd123', 3),
            (now(), now(), True, 'asd123', 4),
            (now(), now(), True, 'asd123', 5)
        ON CONFLICT DO NOTHING;
    """

    dependencies = [
        ('users', '0001_initial'),
        ('restaurants', '0002_auto_20241215_0411'),
    ]

    operations = [
        migrations.RunSQL(SQL, reverse_sql=migrations.RunSQL.noop),
    ]
